[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]
optimizer = true
optimizer_runs = 200

# Remappings for OpenZeppelin contracts
remappings = [
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
    "forge-std/=lib/forge-std/src/"
]

[profile.default.fuzz]
runs = 1000

[profile.default.invariant]
runs = 1000
depth = 15
fail_on_revert = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
